### ISSUE TITLE
TypeError: WebfontPlugin is not a constructor

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [itgalaxy/webfont-webpack-plugin#105]
I am getting the above error when i tried to use this plugin. I am using it as below, after installing it.

````
const WebfontPlugin = require("webfont-webpack-plugin");

new WebfontPlugin({
      files: path.join(__dirname, "static/public/svg_icons/*.svg"),
      dest: path.join(__dirname, "static/public/css"),
      destTemplate: path.resolve(__dirname, "svg-icons.css")
 })
````
Error is
````
throw err;
^
TypeError: WebfontPlugin is not a constructor
````

**Comment by evilebottnawi** [comment]
@rajeshwarpatlolla 
use
```
const WebfontPlugin = require("webfont-webpack-plugin").default;
```
for files in cjs format. Can't be fixed right now, will be fixed for cjs env in next major release. Thanks

**Comment by rajeshwarpatlolla** [comment]
Still it's not generating the css file. My configuration is as below.

````
const WebfontPlugin = require("webfont-webpack-plugin").default;

new WebfontPlugin({
  files: path.join(__dirname, "static/public/svg_icons/*.svg"),
  dest: path.join(__dirname, "static/public/css"),
  destTemplate: path.resolve(__dirname, "svg-icons.css")
})
````

**Comment by evilebottnawi** [comment]
@rajeshwarpatlolla node version? Right now it is broken in `10.0.0` due problem in deps

**Comment by rajeshwarpatlolla** [comment]
I am using node v8.10.0

**Comment by evilebottnawi** [comment]
@rajeshwarpatlolla Do you add `@import "webfont.scss";` in some `scss` file?

**Comment by rajeshwarpatlolla** [comment]
No, Is it ok, if we add it in anyscss file?

**Comment by evilebottnawi** [comment]
@rajeshwarpatlolla better place is shared `scss` file between multiple entry points. If you have one entry point better to add in top of `scss` file

**Comment by rajeshwarpatlolla** [comment]
Getting this error after adding it in the main scss file.

![screen shot 2018-05-02 at 9 09 11 pm](https://user-images.githubusercontent.com/9896335/39533597-19257af8-4e4d-11e8-8b15-a66d47697abb.png)

**Comment by evilebottnawi** [comment]
@rajeshwarpatlolla based on your config please use `@import "static/public/css/svg-icons.css"` or other way.
How plugin works:
1. Glob all svg icons
2. Create fonts and css.
3. You should import `css` in any place in you `scss/css` main file.

Please learn to read README. Thanks!

**Comment by rajeshwarpatlolla** [comment]
Without reading it i wouldn't even setup the config btw. And i feel the README is not very clear to set it up. It doesn't give any info about `import "webfont.css";`.

Even the changes you mentioned, it's not generating the css file itself

**Comment by evilebottnawi** [comment]
@rajeshwarpatlolla feel free to send PR to improve readme. Sometimes it's hard to explain some things

**Comment by rajeshwarpatlolla** [comment]
Yeah, u r right. I know as an open source contributor.
Could you please look into this issue? What is not allowing to generate the css file from svg with my config?

**Comment by evilebottnawi** [comment]
@rajeshwarpatlolla Can you provide minimum reproducible test repo? I would be able to show you exactly what is wrong and maybe it would give an idea of how best to document this

**Comment by rajeshwarpatlolla** [comment]
I may not be able to share the repo, as it is a private project, and moreover i do not have admin access. But i can share the complete setup i made.
Folder structure is like below
![screen shot 2018-05-02 at 10 00 25 pm](https://user-images.githubusercontent.com/9896335/39536501-67228d52-4e54-11e8-9816-7eb64cfc87d4.png)

In my webpack i added 

````
const WebfontPlugin = require("webfont-webpack-plugin").default;
````
And the plugins are configured like this
````
plugins: [
    new MiniCssExtractPlugin({
      // Options similar to the same options in webpackOptions.output both options are optional
      // path: path.resolve(__dirname, "sfa_gui/static/public/css"),
      filename: "css/application.css",
      chunkFilename: "[name].css"
    }),
    new ProgressBarPlugin(),
    new WebfontPlugin({
      files: path.join(__dirname, "sfa_gui/static/public/svg_icons/*.svg"),
      dest: path.join(__dirname, "sfa_gui/static/public/css"),
      destTemplate: path.resolve(__dirname, "sfa_gui/static/public/css")
      // destTemplate: path.resolve(__dirname, "svg-icons.css") // tried with this too
    })
  ]
````

But still it is not generating the css file which i am expecting.

**Comment by evilebottnawi** [comment]
@rajeshwarpatlolla i.e. `css` file not generated, right?

**Comment by rajeshwarpatlolla** [comment]
Yes, it is not generating the css file.

**Comment by evilebottnawi** [comment]
@rajeshwarpatlolla can you add `template: "css"` to options?

**Comment by rajeshwarpatlolla** [comment]
It is generating many files now, instead of one single css file which should include all the svg files present in `svg_icons` folder.
![screen shot 2018-05-02 at 10 26 05 pm](https://user-images.githubusercontent.com/9896335/39537643-d73edfca-4e57-11e8-994c-37fa7a2dbb5d.png)

**Comment by evilebottnawi** [comment]
@rajeshwarpatlolla it should be generate multiple files, each font is separate file

**Comment by evilebottnawi** [comment]
@rajeshwarpatlolla it seems like you just do not understand how the generation of font fonts from icons works, please read about this in short way here https://github.com/itgalaxy/webfont
