### ISSUE TITLE
Need cssDest dest file

### ISSUE THREAD

**Issue by bazilyuk** [itgalaxy/webfont-webpack-plugin#134]
I have template file (template: resolvePath(COMMON_DIR, 'markup/common/scss/ico/_ico-template1.scss')) when I build project, that file rewrites. But I need 2 different files, one for template and one generated file. Because If I build project ones with that template I can't build it second time, because that file is rewrote!
Do you have that option?

**Comment by alexander-akait** [comment]
Duplicate https://github.com/itgalaxy/webfont/issues/189
