### ISSUE TITLE
Plugin isn't generating any css or scss files

### ISSUE THREAD

**Issue by cyr-x** [itgalaxy/webfont-webpack-plugin#7]
**I'm submitting a ...** 
```
[x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
The plugin isn't generating any css or scss files (tried both). I tried the following configurations:

```js
new WebfontPlugin({
    files: root('./assets/icons/*.svg'),
    css: true,
    fontName: 'icons.font',
    dest: {
      fontsDir: root('./fonts'),
      stylesDir: root('./css')
    }
})
```
```js
new WebfontPlugin({
    files: root('./assets/icons/*.svg'),
    css: true,
    cssFormat: 'scss',
    fontName: 'icons.font',
    dest: {
      fontsDir: root('./fonts'),
      stylesDir: root('./css')
    }
})
```
Maybe i'm missing something, the docs aren't that accurate.

**Expected behavior**
It should generate the css or scss file in the `css` directory, but the `result.styles` is undefined. (insterted a `console.log` into WebfontPlugin.js.
* **plugin version:** 0.0.1-alpha.7

* **webpack version:** 2.2.0-rc.3

* **Language:** TypeScript 2.0

**Comment by evilebottnawi** [comment]
@kevinwardenga thanks for feedback, i will try to investigate the issue today

**Comment by kevinwardenga** [comment]
Found it myself, the docs are wrong, the following config is working (got it from `src/__tests__`:
```js
 new WebfontPlugin({
    files: root('./assets/icons/*.svg'),
    css: true,
    template: 'scss',
    fontName: 'icons',
    cssTemplateFontPath: '../fonts/',
    dest: {
      fontsDir: root('./assets/fonts'),
      stylesDir: root('./assets/styles')
    }
  })
```

Its you neet to change `cssFormat` to `template`.

But now if i'm importing the generated scss | css file into my css its producing an endless loop due to watcher is thinking the file has changed, then generates the file again and thinks its changed again.

**Comment by evilebottnawi** [comment]
@kevinwardenga i know about this bug, i am use:
```js
new webpack.WatchIgnorePlugin([
    /src\/shared\/fonts\/icon-font\..*/,
    /src\/shared\/styles\/fonts\/_icon-font\.scss/
]),
```
If you have idea how do this without infinity refreshing send PR and we solved this problem :smile:
